### PR TITLE
Allow running the buildpack locally or from GIT

### PR DESCRIPTION
**Pull request by dmathieu**
This implements https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000006cBxbIAE/view

> As a buildpack user
> I should be able to use the node-function-buildpack Github as a buildpack w/o compiling

Based on [bin/bootstrap from java-buildpack](https://github.com/heroku/java-buildpack/blob/master/bin/bootstrap).
The only difference from there is that I haven't gone with installing Go. Instead, I check that it's there and using the version we expect in `go.mod`. That way, the script can work on any platform.

This is based after #12

### CODE REVIEW

**Comment by jkutner** [comment]
This is good as a first step, but we also need something that will call the `bin/bootstrap`. This might mean having a thin `bin/build` bash script that either calls `bin/bootstrap` or the precompiled binary.

Here's an example:
https://github.com/heroku/java-buildpack/blob/master/bin/build#L23-L30

**Comment by dmathieu** [comment]
Sure. I did it like this because that's how it was described in the card.
Could you describe a bit more what you're trying to achieve? (do we want to package and release the buildpack, or be able to run it locally?) that'll help me have something working as you expect it instead of going back and forth.

**Comment by jkutner** [comment]
Sure we can pause on this if you want to wait until I can provide a better explaination, but I'll try here.

We want to support both precompiled versions of this buildpack, and from versions from source (such as when the Github URL is used as a pointer to this buildpack).

The precompiled buildpack will contain the compiled `bin/build` binary. But the source from the Github URL will not. So we need a mechanism that will look at the filesystem and see that the compiled binaries aren't there, and then compile them on the fly (that's the `bin/bootstrap`).

To support this, we need to change the name of the `bin/build` binary to something like `bin/builder`, and make `bin/build` a simple Bash script containing the snippet I shared earlier (which calls `bin/bootstrap` if it can't find the `bin/builder` binary.

I hope this helps.

**Comment by dmathieu** [comment]
@jkutner I've updated this PR to fully allow running locally or from GIT without the compiled binaries.

**Pull request merged**
