### PR TITLE
Adding support for TypeScript functions.

### PR DESCRIPTION
**Pull request by mmillersf**
Modified the detect code to looks for *.ts files as well as *.js files. Modified the validatePackageJson code to support "Main" being a generated javascript file in a target directory rather than a file in the application root.

### CODE REVIEW

**Comment by jkutner** [comment]
@mmillersf sorry, didn't notice this one

**Comment by hone** [comment]
Should we also fix up [this error message](https://github.com/heroku/node-function-buildpack/blob/8e018fb060c590c297fca8597d385a729e5addde/node/detect.go#L54) to say `js` or `ts` files?

**Comment by mmillersf** [comment]
Good call on the error message. I looked over the source and didn't see any other references just to Javascript.

**Comment by mmillersf** [comment]
@jkutner is anything else needed to get this pull request merged?

**Comment by jkutner** [comment]
@hone @elbandito can you both approve when you're ready and then merge?

**Comment by elbandito** [comment]
LGTM 🏄

**Pull request merged**
