### PR TITLE
fix: don't hardcode HOST and HTTP_PORT into the image layer

### PR DESCRIPTION
**Pull request by elbandito**

### CODE REVIEW

**Comment by elbandito** [comment]
I wonder if I should use a different ENV var name like `FUNC_PORT` or just `PORT`.

**Comment by hone** [comment]
I think this may not be what you think it is. This means you'd have to specify `HTTP_PORT` at build time and it'd get written into the launch. I think instead, you'd want to maybe write a `profile.d/` script so you can set it at runtime by reading the env var.

**Comment by elbandito** [comment]
One other thing that I just realized is that the user would have to re-build their function anytime they wanted to change the `HTTP_PORT`, which is a pain.

**Comment by hone** [comment]
Yeah, which is why I think you intentionally meant for this to be done at runtime vs build time.

**Comment by elbandito** [comment]
Please let me know if I'm missing something,  but I don't think there's any need to set the `HTTP_PORT` in the image layer.

By removing this from the image layer, I'm able to dynamically set the port via ENV at runtime for both Docker and Knative.  Instead, I'm leaning towards defaulting to `8080` in the invoker code if no ENV var is set.

**Comment by elbandito** [comment]
Please let me know if I'm missing something,  but I don't think there's any need to set the `HTTP_PORT` in the image layer.

By removing this from the image layer, I'm able to dynamically set the port via ENV at runtime for both Docker and Knative.  Instead, I'm leaning towards defaulting to `8080` in the invoker code if no ENV var is set.

**Comment by hone** [comment]
Yeah that should work. Do we want `HTTP_PORT` or just `PORT` /cc @jkutner

**Comment by jkutner** [comment]
`PORT` to align with https://github.com/buildpack/spec/pull/42

**Comment by elbandito** [comment]
@hone and @jkutner here are the latest changes to remove both the `HTTP_PORT` and `HOST` values from the image layer.  I also updated to the latest node invoker release, which contains my corresponding changes to set their default values in the invoker server setup.

**Pull request merged**
