### PR TITLE
feat: inspect for remote debugging

### PR DESCRIPTION
**Pull request by elbandito**

### CODE REVIEW

**Comment by elbandito** [comment]
@joshwlewis I'm wondering if the ENV var `debug` is overloaded, and maybe I should use `debugger` instead.

**Comment by jabrown85** [comment]
Should this maybe be a PR to the node-engine buildpack instead? I'm worried about it being in this buildpack that we plan on ultimately removing once we can reliably use the existing riff buildpacks. Or maybe we should shim the `node` executable similarly to how we [do it for chrome](https://github.com/heroku/heroku-buildpack-google-chrome/blob/master/bin/compile#L172)

**Comment by elbandito** [comment]
@jabrown85 potentially maybe it could/should go into the node buildpack.  My approach to this change is very short term in that we add it now to the `node-function-buildpack` for the time being then when we move to riff master we re-examine whether or not it makes sense to add this to node, or the CNB /bin/dev.

**Comment by elbandito** [comment]
For now, we can just set the `NODE_OPTIONS` ENV var

**Pull request closed without merging**
